# Generated by Django 5.2.3 on 2026-04-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_subscriptionplan_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
