# Generated by Django 5.2 on 2026-04-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_coupon_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
