# Generated by Django 5.2 on 2026-04-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_alter_service_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='tier',
            field=models.CharField(default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tier',
            field=models.CharField(default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='has_tier_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='has_tier_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='tier_2_delivery_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='tier_2_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='tier_2_name',
            field=models.CharField(default='Gold', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='tier_2_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='tier_3_delivery_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='tier_3_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='tier_3_name',
            field=models.CharField(default='Imperial', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='tier_3_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
