# Generated by Django 5.2 on 2026-04-06 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_customoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermessage',
            name='custom_offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_message', to='services.customoffer'),
        ),
    ]
